project_id = "vsqiuwbmawygkxxjrxnt"

[functions]

[functions.process-import-rows]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.generate-reminders]
verify_jwt = false
